spring:
  application:
    name: spring-cloud-CapitalNameService
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:7010/eureka}
  instance:
    preferIpAddress: true